Repository teamsparta-hangry/hangry, pull requests merged in 2025-04, with the labels that each got.

#11 Feat/reservation 8 create entity
  common/src/main/java/com/waitless/common/entity/BaseTimeEntity.java
  reservation-service/build.gradle
  reservation-service/src/main/java/com/waitless/reservation/ReservationApplication.java
  reservation-service/src/main/java/com/waitless/reservation/domain/entity/.gitKeep
  reservation-service/src/main/java/com/waitless/reservation/domain/entity/Reservation.java
  reservation-service/src/main/java/com/waitless/reservation/domain/entity/ReservationMenu.java
  reservation-service/src/main/java/com/waitless/reservation/domain/entity/ReservationStatus.java
  reservation-service/src/main/resources/application.properties
  reservation-service/src/main/resources/application.yml
Labels: feature

#14 Feature/review-7-init
  benefit-service/src/main/java/com/waitless/benefit/point/domain/entity/.gitKeep
  benefit-service/src/main/java/com/waitless/benefit/point/domain/entity/Point.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/vo/PointAmount.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/vo/PointType.java
  review-service/src/main/java/com/waitless/review/domain/entity/.gitKeep
  review-service/src/main/java/com/waitless/review/domain/entity/Review.java
  review-service/src/main/java/com/waitless/review/domain/vo/Rating.java
  review-service/src/main/java/com/waitless/review/domain/vo/ReviewType.java
Labels: good first issue, feature

#25 Feat/review 21 refactor: 리뷰/포인트 Auditing 추가 및 리팩토링
  benefit-service/build.gradle
  benefit-service/src/main/java/com/waitless/benefit/BenefitApplication.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/entity/Point.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/vo/PointAmount.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/vo/PointType.java
  benefit-service/src/main/resources/application.properties
  benefit-service/src/main/resources/application.yml
  common/build.gradle
  common/src/main/java/com/waitless/common/domain/BaseTimeEntity.java
  reservation-service/src/main/java/com/waitless/reservation/domain/entity/Reservation.java
  restaurant-service/src/main/java/com/waitless/restaurant/menu/domain/entity/Menu.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/entity/Category.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/entity/Restaurant.java
  review-service/build.gradle
  review-service/src/main/java/com/waitless/review/ReviewApplication.java
  review-service/src/main/java/com/waitless/review/domain/entity/Review.java
  review-service/src/main/java/com/waitless/review/domain/vo/Rating.java
  review-service/src/main/java/com/waitless/review/domain/vo/ReviewType.java
  review-service/src/main/resources/application.properties
  review-service/src/main/resources/application.yml
Labels: feature

#30 feat : 유저 회원가입
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  settings.gradle
  user-service/build.gradle
  user-service/settings.gradle
  user-service/src/main/java/com/waitless/user/UserApplication.java
  user-service/src/main/java/com/waitless/user/application/dto/.gitKeep
  user-service/src/main/java/com/waitless/user/application/dto/SignupDto.java
  user-service/src/main/java/com/waitless/user/application/dto/SignupResponseDto.java
  user-service/src/main/java/com/waitless/user/application/mapper/UserServiceMapper.java
  user-service/src/main/java/com/waitless/user/application/service/.gitKeep
  user-service/src/main/java/com/waitless/user/application/service/UserService.java
  user-service/src/main/java/com/waitless/user/application/service/UserServiceImpl.java
  user-service/src/main/java/com/waitless/user/domain/entity/.gitKeep
  user-service/src/main/java/com/waitless/user/domain/entity/Role.java
  user-service/src/main/java/com/waitless/user/domain/entity/User.java
  user-service/src/main/java/com/waitless/user/domain/repository/.gitKeep
  user-service/src/main/java/com/waitless/user/domain/repository/UserRepository.java
  user-service/src/main/java/com/waitless/user/infrastructure/config/.gitKeep
  user-service/src/main/java/com/waitless/user/infrastructure/config/SecurityConfig.java
  user-service/src/main/java/com/waitless/user/infrastructure/repository/JpaUserRepository.java
  user-service/src/main/java/com/waitless/user/infrastructure/repository/UserRepositoryImpl.java
  user-service/src/main/java/com/waitless/user/presentation/controller/UserController.java
  user-service/src/main/java/com/waitless/user/presentation/dto/.gitKeep
  user-service/src/main/java/com/waitless/user/presentation/dto/SignupRequestDto.java
  user-service/src/main/java/com/waitless/user/presentation/mapper/UserControllerMapper.java
  user-service/src/main/resources/application.properties
  user-service/src/main/resources/application.yml
  user-service/src/main/resources/http/test.http
  user-service/src/test/java/com/waitless/user/UserApplicationTests.java
Labels: feature

#32 [Feat] 식당 생성 API 추가
  restaurant-service/build.gradle
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/.gitKeep
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/CreateRestaurantDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/CreateRestaurantResponseDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/mapper/RestaurantServiceMapper.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/CategoryService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/CategoryServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/entity/Category.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/entity/Restaurant.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/repository/CategoryRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/repository/RestaurantRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/vo/Location.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/vo/OperatingHours.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/CategoryJpaRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/CategoryRepositoryImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/RestaurantJpaRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/RestaurantRepositoryImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/RestaurantController.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/dto/.gitKeep
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/dto/CreateRestaurantRequestDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/mapper/RestaurantControllerMapper.java
  restaurant-service/src/main/resources/category.sql
Labels: feature

#44 feat: 식당 Update API 추가
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/CreateRestaurantDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/CreateRestaurantResponseDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/RestaurantResponseDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/UpdateRestaurantDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/mapper/RestaurantServiceMapper.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/entity/Category.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/entity/Restaurant.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/repository/RestaurantRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/vo/Location.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/vo/OperatingHours.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/RestaurantRepositoryImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/RestaurantController.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/dto/UpdateRestaurantRequestDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/mapper/RestaurantControllerMapper.java
Labels: feature

#42 feat: 리뷰 생성 API 구현
  review-service/build.gradle
  review-service/src/main/java/com/waitless/review/application/dto/.gitKeep
  review-service/src/main/java/com/waitless/review/application/dto/command/PostReviewCommand.java
  review-service/src/main/java/com/waitless/review/application/dto/result/PostReviewResult.java
  review-service/src/main/java/com/waitless/review/application/mapper/ReviewServiceMapper.java
  review-service/src/main/java/com/waitless/review/application/service/.gitKeep
  review-service/src/main/java/com/waitless/review/application/service/ReviewService.java
  review-service/src/main/java/com/waitless/review/application/service/ReviewServiceImpl.java
  review-service/src/main/java/com/waitless/review/domain/repository/.gitKeep
  review-service/src/main/java/com/waitless/review/domain/repository/ReviewRepository.java
  review-service/src/main/java/com/waitless/review/infrastructure/persistence/JpaReviewRepository.java
  review-service/src/main/java/com/waitless/review/presentation/controller/ReviewExternalController.java
  review-service/src/main/java/com/waitless/review/presentation/dto/.gitKeep
  review-service/src/main/java/com/waitless/review/presentation/dto/request/PostReviewRequestDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/response/PostReviewResponseDto.java
  review-service/src/main/java/com/waitless/review/presentation/mapper/ReviewControllerMapper.java
  review-service/src/main/resources/application.yml
Labels: feature

#49 feat: 식당 단건 조회 API 추가
  restaurant-service/src/main/java/com/waitless/restaurant/menu/application/mapper/MenuServiceMapper.java
  restaurant-service/src/main/java/com/waitless/restaurant/menu/application/service/MenuService.java
  restaurant-service/src/main/java/com/waitless/restaurant/menu/application/service/MenuServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/RestaurantWithMenuResponseDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/mapper/RestaurantServiceMapper.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/RestaurantController.java
Labels: feature

#47 feat: 식당 삭제 API 추가
  restaurant-service/src/main/java/com/waitless/restaurant/menu/application/service/MenuService.java
  restaurant-service/src/main/java/com/waitless/restaurant/menu/application/service/MenuServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/RestaurantController.java
Labels: feature

#46 Feat/reservation 17 create reservation
  common/src/main/java/com/waitless/common/exception/BusinessException.java
  common/src/main/java/com/waitless/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/waitless/common/exception/response/SingleResponse.java
  docker-compose.yml
  reservation-service/build.gradle
  reservation-service/src/main/java/com/waitless/reservation/ReservationApplication.java
  reservation-service/src/main/java/com/waitless/reservation/application/dto/.gitKeep
  reservation-service/src/main/java/com/waitless/reservation/application/dto/LuaResultType.java
  reservation-service/src/main/java/com/waitless/reservation/application/dto/ReservationCreateCommand.java
  reservation-service/src/main/java/com/waitless/reservation/application/mapper/ReservationServiceMapper.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/.gitKeep
  reservation-service/src/main/java/com/waitless/reservation/application/service/command/ReservationCommandService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/command/ReservationCommandServiceImpl.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/query/ReservationQueryService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/query/ReservationQueryServiceImpl.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/redis/DummyReservationNumberLoader.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/redis/DummyStockLoader.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/redis/RedisLuaScriptService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/redis/RedisReservationService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/redis/RedisStockService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/redis/RedisStockServiceImpl.java
  reservation-service/src/main/java/com/waitless/reservation/domain/entity/Reservation.java
  reservation-service/src/main/java/com/waitless/reservation/domain/entity/ReservationMenu.java
  reservation-service/src/main/java/com/waitless/reservation/domain/repository/.gitKeep
  reservation-service/src/main/java/com/waitless/reservation/domain/repository/ReservationRepository.java
  reservation-service/src/main/java/com/waitless/reservation/exception/exception/ReservationErrorCode.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/in/.gitKeep
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/out/.gitKeep
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/repository/ReservationJpaRepository.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/repository/ReservationRepositoryImpl.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/config/.gitKeep
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/config/redis/RedisConfig.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/aop/ControllerLoggingAspect.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/controller/external/ReservationExternalController.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/dto/.gitKeep
  reservation-service/src/main/java/com/waitless/reservation/presentation/dto/ReservationCreateRequest.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/dto/ReservationCreateResponse.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/mapper/ReservationCommandMapper.java
  reservation-service/src/main/resources/application.yml
  reservation-service/src/main/resources/lua/stock_decrease.lua
  reservation-service/src/test/java/com/waitless/reservation/application/service/command/ReservationCommandServiceImplTest.java
Labels: feature

#69 Feat/reservation 53 find one
  reservation-service/src/main/java/com/waitless/reservation/application/dto/ReservationCreateResponse.java
  reservation-service/src/main/java/com/waitless/reservation/application/mapper/ReservationMenuServiceMapper.java
  reservation-service/src/main/java/com/waitless/reservation/application/mapper/ReservationServiceMapper.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/query/ReservationQueryService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/query/ReservationQueryServiceImpl.java
  reservation-service/src/main/java/com/waitless/reservation/domain/entity/Reservation.java
  reservation-service/src/main/java/com/waitless/reservation/domain/entity/ReservationMenu.java
  reservation-service/src/main/java/com/waitless/reservation/domain/repository/ReservationRepository.java
  reservation-service/src/main/java/com/waitless/reservation/exception/exception/ReservationErrorCode.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/repository/ReservationJpaRepository.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/repository/ReservationRepositoryImpl.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/controller/external/ReservationExternalController.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/dto/ReservationFindResponse.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/dto/ReservationMenuResponse.java
Labels: feature

#67 Feat/user 65 update & delete
  user-service/src/main/java/com/waitless/user/application/service/UserService.java
  user-service/src/main/java/com/waitless/user/application/service/UserServiceImpl.java
  user-service/src/main/java/com/waitless/user/domain/entity/User.java
  user-service/src/main/java/com/waitless/user/presentation/controller/UserController.java
  user-service/src/main/resources/http/test.http
Labels: feature

#64 feat: 식당 전체 및 검색 추가
  restaurant-service/settings.gradle
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/SearchRestaurantDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/mapper/RestaurantServiceMapper.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/repository/RestaurantQueryRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/config/.gitKeep
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/config/QueryDslConfig.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/RestaurantQueryRepositoryImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/RestaurantController.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/dto/SearchRestaurantRequestDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/mapper/RestaurantControllerMapper.java
Labels: feature

#75 feat:리뷰생성->Kafka이벤트발행->포인트적립
  benefit-service/build.gradle
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/.gitKeep
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/command/PostPointCommand.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/result/PostPointResult.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/service/.gitKeep
  benefit-service/src/main/java/com/waitless/benefit/point/application/service/PointService.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/service/PointServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/repository/.gitKeep
  benefit-service/src/main/java/com/waitless/benefit/point/domain/repository/PointRepository.java
  benefit-service/src/main/java/com/waitless/benefit/point/infrastructure/adaptor/in/.gitKeep
  benefit-service/src/main/java/com/waitless/benefit/point/infrastructure/adaptor/in/messaging/ReviewCreatedEventHandler.java
  benefit-service/src/main/java/com/waitless/benefit/point/infrastructure/persistence/JpaPointRepository.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/dto/.gitKeep
  benefit-service/src/main/resources/application.yml
  common/src/main/java/com/waitless/common/event/Event.java
  common/src/main/java/com/waitless/common/event/ReviewCreatedEvent.java
  common/src/main/java/com/waitless/common/event/ReviewDeletedEvent.java
  review-service/build.gradle
  review-service/src/main/java/com/waitless/review/application/port/out/ReviewEventPublisher.java
  review-service/src/main/java/com/waitless/review/application/service/ReviewServiceImpl.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/in/.gitKeep
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/.gitKeep
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/messaging/ReviewEventPublisherImpl.java
  review-service/src/main/java/com/waitless/review/infrastructure/config/.gitKeep
  review-service/src/main/resources/application.yml
Labels: feature

#77 feat : 쿠폰 생성
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/dto/CouponResponseDto.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/dto/CreateCouponDto.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/mapper/CouponServiceMapper.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/.gitKeep
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponService.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/entity/.gitKeep
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/entity/Coupon.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/entity/CouponHistory.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/repository/.gitKeep
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/repository/CouponRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/CouponRepositoryImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/JpaCouponRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/controller/CouponController.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/dto/.gitKeep
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/dto/CreateCouponRequestDto.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/mapper/CouponControllerMapper.java
  benefit-service/src/main/resources/http/coupon-test.http
Labels: feature

#84 Feat/coupon 83 read & update
  auth-service/src/main/java/com/waitless/auth/infrastructure/security/AuthenticationFilter.java
  benefit-service/build.gradle
  benefit-service/settings.gradle
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/dto/.gitKeep
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/dto/CouponResponseDto.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/dto/ReadCouponsDto.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/exception/CouponBusinessException.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/exception/CouponErrorCode.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/mapper/CouponServiceMapper.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponService.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/entity/Coupon.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/repository/CouponRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/CouponRepositoryImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/CustomCouponRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/controller/CouponController.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/dto/ReadCouponsRequestDto.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/mapper/CouponControllerMapper.java
  benefit-service/src/main/resources/http/coupon-test.http
  gateway/src/main/resources/application.yml
Labels: feature

#87 feat : coupon 쿠폰 삭제
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponService.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/controller/CouponController.java
  benefit-service/src/main/resources/http/coupon-test.http
Labels: feature

#78 feat: 식당 재고 조회 추가
  common/src/main/java/com/waitless/common/dto/RestaurantStockResponseDto.java
  common/src/main/java/com/waitless/common/dto/StockDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/CreateRestaurantDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/RestaurantResponseDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/mapper/RestaurantServiceMapper.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/entity/Restaurant.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/repository/RestaurantRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/config/QueryDslConfig.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/RestaurantJpaRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/RestaurantRepositoryImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/RestaurantController.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/dto/CreateRestaurantRequestDto.java
Labels: feature

#91 식당 재고 감소 구현
  restaurant-service/build.gradle
  restaurant-service/src/main/java/com/waitless/restaurant/RestaurantApplication.java
  restaurant-service/src/main/java/com/waitless/restaurant/menu/application/service/MenuService.java
  restaurant-service/src/main/java/com/waitless/restaurant/menu/application/service/MenuServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/menu/domain/entity/Menu.java
  restaurant-service/src/main/java/com/waitless/restaurant/menu/infrastructure/adaptor/in/.gitKeep
  restaurant-service/src/main/java/com/waitless/restaurant/menu/infrastructure/adaptor/in/messaging/StockDecreaseEventHandler.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/exception/RestaurantBusinessException.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/exception/RestaurantErrorCode.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/RestaurantController.java
  restaurant-service/src/main/resources/application.yml
Labels: feature

#88 Feat/쿠폰 발급 받기
  auth-service/src/main/java/com/waitless/auth/application/service/AuthServiceImpl.java
  auth-service/src/main/java/com/waitless/auth/application/service/TokenManager.java
  auth-service/src/main/java/com/waitless/auth/infrastructure/config/SecurityConfig.java
  auth-service/src/main/java/com/waitless/auth/infrastructure/security/AuthenticationFilter.java
  auth-service/src/main/java/com/waitless/auth/infrastructure/security/JwtTokenManager.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/dto/CouponHistoryResponseDto.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/dto/CouponInfoDto.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/exception/CouponErrorCode.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/mapper/CouponHistoryServiceMapper.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/mapper/CouponServiceMapper.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponHistoryService.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponHistoryServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponService.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/entity/Coupon.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/entity/CouponHistory.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/repository/CouponHistoryRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/CouponHistoryRepositoryImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/JpaCouponHistoryRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/controller/CouponController.java
  benefit-service/src/main/resources/http/coupon-test.http
  user-service/build.gradle
Labels: feature

#89 Feat/reservation 81 ticketing create
  reservation-service/src/main/java/com/waitless/reservation/ReservationApplication.java
  reservation-service/src/main/java/com/waitless/reservation/application/dto/CancelMenuDto.java
  reservation-service/src/main/java/com/waitless/reservation/application/dto/TicketCreateServiceRequest.java
  reservation-service/src/main/java/com/waitless/reservation/application/dto/TicketCreateServiceResponse.java
  reservation-service/src/main/java/com/waitless/reservation/application/mapper/TicketServiceMapper.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/command/ReservationCommandService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/command/ReservationCommandServiceImpl.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/redis/RedisReservationQueueService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/redis/RedisStockService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/redis/RedisStockServiceImpl.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/ticket/TicketService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/ticket/TicketServiceImpl.java
  reservation-service/src/main/java/com/waitless/reservation/domain/entity/Reservation.java
  reservation-service/src/main/java/com/waitless/reservation/domain/entity/TicketRestaurant.java
  reservation-service/src/main/java/com/waitless/reservation/domain/repository/TicketRepository.java
  reservation-service/src/main/java/com/waitless/reservation/exception/exception/ReservationErrorCode.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/client/RestaurantClient.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/repository/TicketJpaRepository.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/repository/TicketRepositoryImpl.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/config/feign/RestaurantClientErrorDecoder.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/config/feign/RestaurantFeignConfig.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/controller/external/ReservationExternalController.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/controller/internal/ReservationInternalController.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/dto/TicketCreateRequest.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/mapper/TicketMapper.java
  reservation-service/src/main/resources/application.yml
  reservation-service/src/main/resources/lua/stock_increment.lua
Labels: feature

#93 Feat/90 쿠폰발급내역 조회
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/dto/ReadCouponHistoriesDto.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/exception/CouponErrorCode.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/mapper/CouponHistoryServiceMapper.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponHistoryService.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponHistoryServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/entity/CouponHistory.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/repository/CouponHistoryRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/repository/CouponRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/CouponHistoryRepositoryImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/CouponRepositoryImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/CustomCouponHistoryRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/controller/CouponController.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/dto/ReadCouponHistoriesRequestDto.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/mapper/CouponControllerMapper.java
  benefit-service/src/main/resources/http/coupon-test.http
Labels: feature

#101 feat: 카테고리 생성, 전체 조회 api
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/CategoryResponseDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/exception/RestaurantErrorCode.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/mapper/CategoryServiceMapper.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/CategoryService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/CategoryServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/entity/Category.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/repository/CategoryRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/CategoryJpaRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/CategoryRepositoryImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/CategoryController.java
Labels: feature

#103 feat: internal 식당 조회 api 추가
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/external/RestaurantExternalController.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/internal/RestaurantInternalController.java
Labels: feature

#104 Feat/ch 94 delete
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/exception/CouponErrorCode.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponHistoryService.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponHistoryServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponScheduler.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/CouponHistoryRepositoryImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/CouponRepositoryImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/CustomCouponHistoryRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/CustomCouponRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/service/CouponSchedulerImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/controller/CouponController.java
  benefit-service/src/main/resources/http/coupon-test.http
Labels: feature

#108 feat: 즐겨찾기 생성
  common/src/main/java/com/waitless/common/domain/BaseTimeEntity.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/FavoriteResponseDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/exception/RestaurantErrorCode.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/mapper/FavoriteServiceMapper.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/FavoriteService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/FavoriteServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/entity/Favorite.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/repository/FavoriteRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/FavoriteJpaRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/FavoriteRepositoryImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/external/FavoriteExternalController.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/dto/FavoriteRequestDto.java
Labels: feature

#106 feat : coupon-history 발급된 쿠폰 사용
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/exception/CouponErrorCode.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponHistoryService.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponHistoryServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/entity/CouponHistory.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/service/CouponSchedulerImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/controller/CouponController.java
  benefit-service/src/main/resources/http/coupon-test.http
Labels: feature

#115 feat: 리뷰 단건/리스트/조건 조회 구현 및 테스트 완료
  benefit-service/src/main/java/com/waitless/benefit/point/infrastructure/adaptor/outbox/entity/PointOutboxMessage.java
  common/build.gradle
  review-service/build.gradle
  review-service/settings.gradle
  review-service/src/main/java/com/waitless/review/application/dto/command/PageCommand.java
  review-service/src/main/java/com/waitless/review/application/dto/result/DeleteReviewResult.java
  review-service/src/main/java/com/waitless/review/application/dto/result/GetReviewListResult.java
  review-service/src/main/java/com/waitless/review/application/dto/result/GetReviewResult.java
  review-service/src/main/java/com/waitless/review/application/dto/result/SearchReviewsResult.java
  review-service/src/main/java/com/waitless/review/application/service/ReviewService.java
  review-service/src/main/java/com/waitless/review/application/service/ReviewServiceImpl.java
  review-service/src/main/java/com/waitless/review/domain/repository/ReviewRepositoryCustom.java
  review-service/src/main/java/com/waitless/review/domain/vo/ReviewSearchCondition.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/config/QuerydslConfig.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/persistence/ReviewRepositoryCustomImpl.java
  review-service/src/main/java/com/waitless/review/presentation/controller/ReviewExternalController.java
  review-service/src/main/java/com/waitless/review/presentation/dto/request/GetReviewListRequestDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/request/GetReviewRequestDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/request/SearchReviewsRequestDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/response/DeleteReviewResponseDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/response/GetReviewListResponseDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/response/GetReviewResponseDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/response/PostReviewResponseDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/response/SearchReviewsResponseDto.java
  review-service/src/main/java/com/waitless/review/presentation/mapper/ReviewControllerMapper.java
Labels: enhancement, feature

#112 feat: 즐겨찾기 조회 + 취소 API 추가
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/exception/RestaurantErrorCode.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/mapper/FavoriteServiceMapper.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/FavoriteService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/FavoriteServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/repository/FavoriteRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/FavoriteJpaRepository.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/persistence/FavoriteRepositoryImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/external/FavoriteExternalController.java
Labels: feature

#116 Feat/ch 110 redis
  auth-service/src/main/resources/application.yml
  benefit-service/build.gradle
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/dto/CouponHistoryCacheDto.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/exception/CouponErrorCode.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/mapper/CouponHistoryServiceMapper.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponHistoryService.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponHistoryServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponService.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/application/service/CouponServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/entity/CouponHistory.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/domain/repository/CouponRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/config/.gitKeep
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/config/RedisConfig.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/config/RedissonConfig.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/CouponRepositoryImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/repository/JpaCouponRepository.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/service/CouponSchedulerImpl.java
  benefit-service/src/main/java/com/waitless/benefit/coupon/presentation/controller/CouponController.java
  benefit-service/src/main/resources/application.yml
  benefit-service/src/main/resources/http/coupon-test.http
Labels: feature

#125 feat: FeignClients 구현 및 예약 검증 로직 추가
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/command/PostPointCommand.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/result/PostPointResult.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/mapper/PointServiceMapper.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/service/PointServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/entity/Point.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/repository/PointRepository.java
  benefit-service/src/main/java/com/waitless/benefit/point/infrastructure/adaptor/in/messaging/ReviewCreatedEventHandler.java
  common/src/main/java/com/waitless/common/event/PointIssuedEvent.java
  common/src/main/java/com/waitless/common/event/PointIssuedFailedEvent.java
  common/src/main/java/com/waitless/common/event/ReviewCreatedEvent.java
  review-service/src/main/java/com/waitless/review/application/dto/client/VisitedReservationRequestDto.java
  review-service/src/main/java/com/waitless/review/application/dto/client/VisitedReservationResponseDto.java
  review-service/src/main/java/com/waitless/review/application/dto/command/PostReviewCommand.java
  review-service/src/main/java/com/waitless/review/application/dto/result/PostReviewResult.java
  review-service/src/main/java/com/waitless/review/application/mapper/ReviewServiceMapper.java
  review-service/src/main/java/com/waitless/review/application/port/out/VisitedReservationPort.java
  review-service/src/main/java/com/waitless/review/application/service/ReviewServiceImpl.java
  review-service/src/main/java/com/waitless/review/domain/entity/Review.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/in/messaging/PointIssuedFailedEventHandler.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/client/ReservationInternalClient.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/client/VisitedReservationClientAdapter.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/client/dto/ReservationServiceRequest.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/client/dto/ReservationServiceResponse.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/client/mapper/VisitedReservationMapper.java
  review-service/src/main/java/com/waitless/review/presentation/dto/request/PostReviewRequestDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/response/PostReviewResponseDto.java
Labels: feature

#124 feat: 재고 감소 보상 트랜잭션 구현
  common/src/main/java/com/waitless/common/event/StockDecreasedEvent.java
  restaurant-service/src/main/java/com/waitless/restaurant/menu/infrastructure/adaptor/in/messaging/StockDecreaseEventHandler.java
  restaurant-service/src/main/java/com/waitless/restaurant/menu/infrastructure/adaptor/out/messaging/StockDecreaseEventPublisher.java
  restaurant-service/src/main/resources/application.yml
Labels: feature

#121 Feat/reservation 114 current number
  reservation-service/src/main/java/com/waitless/reservation/application/dto/ReservationCurrentResponse.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/query/ReservationQueryService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/query/ReservationQueryServiceImpl.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/redis/RedisReservationQueueService.java
  reservation-service/src/main/java/com/waitless/reservation/domain/entity/Reservation.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/controller/external/ReservationExternalController.java
Labels: bug, feature

#136 feat: 인기 식당 리뷰순/평점순 통계 조회 API(내부 호출) 앤드포인트 구현
  review-service/src/main/java/com/waitless/review/application/dto/command/ReviewStatisticsCommand.java
  review-service/src/main/java/com/waitless/review/application/dto/result/ReviewStatisticsResult.java
  review-service/src/main/java/com/waitless/review/application/port/out/ReviewStatisticsCachePort.java
  review-service/src/main/java/com/waitless/review/application/service/ReviewService.java
  review-service/src/main/java/com/waitless/review/application/service/ReviewServiceImpl.java
  review-service/src/main/java/com/waitless/review/domain/repository/ReviewRepositoryCustom.java
  review-service/src/main/java/com/waitless/review/domain/repository/ReviewStatisticsProjection.java
  review-service/src/main/java/com/waitless/review/domain/vo/ReviewStatisticsCache.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/config/RedisConfig.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/persistence/ReviewRepositoryCustomImpl.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/persistence/ReviewStatisticsRedisRepository.java
  review-service/src/main/java/com/waitless/review/presentation/controller/ReviewInternalController.java
  review-service/src/main/java/com/waitless/review/presentation/dto/request/ReviewStatisticsRequestDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/response/ReviewStatisticsResponseDto.java
  review-service/src/main/java/com/waitless/review/presentation/mapper/ReviewControllerMapper.java
  review-service/src/main/resources/application.yml
Labels: feature

#137 feat: 식당 영업 종료 API 추가
  reservation-service/src/main/java/com/waitless/reservation/presentation/controller/internal/ReservationInternalController.java
  restaurant-service/src/main/java/com/waitless/restaurant/RestaurantApplication.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/dto/RestaurantResponseDto.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/exception/RestaurantErrorCode.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantService.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/application/service/RestaurantServiceImpl.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/domain/entity/Restaurant.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/infrastructure/adaptor/in/client/ReservationInternalClient.java
  restaurant-service/src/main/java/com/waitless/restaurant/restaurant/presentation/controller/external/RestaurantExternalController.java
Labels: feature

#145 feat: 식당 http 요청 추가
  common/http-test/restaurant/restaurant.http
  gateway/src/main/resources/application.yml
Labels: feature

#149 feat: review-http, point-http파일 추가
  common/http-test/benefit/point.http
  common/http-test/review/review.http
  review-service/src/main/java/com/waitless/review/application/service/ReviewServiceImpl.java
  review-service/src/main/java/com/waitless/review/presentation/controller/ReviewExternalController.java
  review-service/src/main/java/com/waitless/review/presentation/controller/ReviewInternalController.java
Labels: feature

#155 feat: 예약 검증 로직 리팩토링
  review-service/src/main/java/com/waitless/review/application/service/ReviewServiceImpl.java
  review-service/src/main/java/com/waitless/review/application/validator/VisitedReservationValidator.java
  review-service/src/main/java/com/waitless/review/application/validator/VisitedReservationValidatorImpl.java
Labels: feature

#157 Feat/reservation 133 create reservation kafka
  common/http-test/reservation/reservation.http
  reservation-service/src/main/java/com/waitless/reservation/application/dto/ReservationCreateCommand.java
  reservation-service/src/main/java/com/waitless/reservation/application/dto/ReservationSearchQuery.java
  reservation-service/src/main/java/com/waitless/reservation/application/event/RedisShutdownListener.java
  reservation-service/src/main/java/com/waitless/reservation/application/event/StockEventHandler.java
  reservation-service/src/main/java/com/waitless/reservation/application/event/StockEventProducer.java
  reservation-service/src/main/java/com/waitless/reservation/application/filter/CustomFilter.java
  reservation-service/src/main/java/com/waitless/reservation/application/interceptor/CustomHeaderInterceptor.java
  reservation-service/src/main/java/com/waitless/reservation/application/interceptor/UserContext.java
  reservation-service/src/main/java/com/waitless/reservation/application/scheduler/restarant/TicketingMenuFetchScheduler.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/command/ReservationCommandServiceImpl.java
  reservation-service/src/main/java/com/waitless/reservation/domain/repository/TicketRepository.java
  reservation-service/src/main/java/com/waitless/reservation/exception/exception/ReservationErrorCode.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/client/RestaurantClient.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/client/UserClient.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/repository/ReservationQueryRepositoryImpl.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/repository/TicketJpaRepository.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/repository/TicketRepositoryImpl.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/config/feign/FeignCommonConfig.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/controller/external/ReservationExternalController.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/dto/ReservationCreateRequest.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/dto/ReservationSearchRequest.java
  reservation-service/src/main/resources/application.yml
Labels: feature

#162 feat: 리뷰작성을 위한 예약 단건 조회 로직 구현 #160
  reservation-service/src/main/java/com/waitless/reservation/application/dto/ReservationServiceResponse.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/query/ReservationQueryService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/query/ReservationQueryServiceImpl.java
  reservation-service/src/main/java/com/waitless/reservation/domain/repository/ReservationRepository.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/repository/ReservationJpaRepository.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/repository/ReservationRepositoryImpl.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/controller/internal/ReservationInternalController.java
  reservation-service/src/main/java/com/waitless/reservation/presentation/dto/ReservationServiceRequest.java
Labels: feature

#159 feat: 단건 통계 조회 API -> 배치형 통계 조회 API로 리팩토링
  common/http-test/review/review.http
  common/src/main/java/com/waitless/common/constants/ReviewCacheConstants.java
  common/src/main/java/com/waitless/common/event/DummyEvent.java
  review-service/src/main/java/com/waitless/review/application/dto/command/ReviewStatisticsCommand.java
  review-service/src/main/java/com/waitless/review/application/port/out/ReviewStatisticsCachePort.java
  review-service/src/main/java/com/waitless/review/application/service/ReviewService.java
  review-service/src/main/java/com/waitless/review/application/service/ReviewServiceImpl.java
  review-service/src/main/java/com/waitless/review/application/service/cache/ReviewBatchCache.java
  review-service/src/main/java/com/waitless/review/application/service/cache/ReviewBatchCacheImpl.java
  review-service/src/main/java/com/waitless/review/domain/repository/ReviewRepositoryCustom.java
  review-service/src/main/java/com/waitless/review/domain/vo/ReviewStatisticsCache.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/persistence/ReviewRepositoryCustomImpl.java
  review-service/src/main/java/com/waitless/review/infrastructure/adaptor/out/persistence/ReviewStatisticsRedisRepository.java
  review-service/src/main/java/com/waitless/review/presentation/controller/ReviewInternalController.java
  review-service/src/main/java/com/waitless/review/presentation/dto/request/ReviewStatisticsBatchRequestDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/request/ReviewStatisticsRequestDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/response/ReviewStatisticsBatchResponseDto.java
  review-service/src/main/java/com/waitless/review/presentation/dto/response/ReviewStatisticsResponseDto.java
  review-service/src/main/java/com/waitless/review/presentation/mapper/ReviewControllerMapper.java
Labels: feature

#153 feat: QuerydslConfig 공통모듈에 추가
  common/src/main/java/com/waitless/common/config/QuerydslConfig.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/config/queryDsl/QueryDslConfig.java
  restaurant-service/src/main/java/com/waitless/restaurant/menu/infrastructure/config/QuerydslConfig.java
  review-service/src/main/java/com/waitless/review/ReviewApplication.java
Labels: feature

#168 feat : payment - payment-service 생성
  gateway/src/main/resources/application.yml
  payment-service/.gitattributes
  payment-service/.gitignore
  payment-service/build.gradle
  payment-service/gradlew
  payment-service/gradlew.bat
  payment-service/src/main/java/com/waitless/payment/PaymentApplication.java
  payment-service/src/main/java/com/waitless/payment/application/client/BenefitServiceClient.java
  payment-service/src/main/java/com/waitless/payment/application/dto/CouponHistoryInfoDto.java
  payment-service/src/main/java/com/waitless/payment/application/dto/MakePaymentDto.java
  payment-service/src/main/java/com/waitless/payment/application/dto/PaymentResponseDto.java
  payment-service/src/main/java/com/waitless/payment/application/service/PaymentService.java
  payment-service/src/main/java/com/waitless/payment/application/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/waitless/payment/domain/entity/Payment.java
  payment-service/src/main/java/com/waitless/payment/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/waitless/payment/infrastructure/adaptor/in/.gitKeep
  payment-service/src/main/java/com/waitless/payment/infrastructure/adaptor/out/.gitKeep
  payment-service/src/main/java/com/waitless/payment/infrastructure/repository/JpaPaymentRepository.java
  payment-service/src/main/java/com/waitless/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment-service/src/main/java/com/waitless/payment/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/waitless/payment/presentation/dto/MakePaymentRequestDto.java
  payment-service/src/main/java/com/waitless/payment/presentation/mapper/PaymentControllerMapper.java
  payment-service/src/main/resources/application.yml
  payment-service/src/test/java/com/waitless/payment/PaymentApplicationTests.java
  settings.gradle
Labels: feature

#173 feat: 포인트 단건/리스트/총합/상위랭킹/본인랭킹 조회 API 추가
  benefit-service/src/main/java/com/waitless/benefit/coupon/infrastructure/config/CouponRedisConfig.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/command/GetMyRankingCommand.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/command/GetPointAmountCommand.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/command/PageCommand.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/command/SearchRankingCommand.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/result/GetMyRankingResult.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/result/GetPointAmountResult.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/result/GetPointListResult.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/result/GetPointResult.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/dto/result/SearchRankingResult.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/port/out/PointRankingCachePort.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/port/out/PointStatisticsCachePort.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/service/PointQueryService.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/service/PointQueryServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/service/PointServiceImpl.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/service/cache/PointQueryCache.java
  benefit-service/src/main/java/com/waitless/benefit/point/application/service/cache/PointQueryCacheImpl.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/repository/PointRepositoryCustom.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/repository/PointStatisticsProjection.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/vo/PointAmountCache.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/vo/PointRankingCache.java
  benefit-service/src/main/java/com/waitless/benefit/point/domain/vo/PointSearchCondition.java
  benefit-service/src/main/java/com/waitless/benefit/point/infrastructure/adaptor/out/config/PointRedisConfig.java
  benefit-service/src/main/java/com/waitless/benefit/point/infrastructure/adaptor/out/persistence/PointRankingRedisRepository.java
  benefit-service/src/main/java/com/waitless/benefit/point/infrastructure/adaptor/out/persistence/PointRepositoryCustomImpl.java
  benefit-service/src/main/java/com/waitless/benefit/point/infrastructure/adaptor/out/persistence/PointStatisticsRedisRepository.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/controller/PointExternalController.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/dto/request/GetMyRankingRequestDto.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/dto/request/GetPointAmountRequestDto.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/dto/request/GetPointListRequestDto.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/dto/request/GetPointRequestDto.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/dto/request/SearchRankingRequestDto.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/dto/response/GetMyRankingResponseDto.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/dto/response/GetPointAmountResponseDto.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/dto/response/GetPointListResponseDto.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/dto/response/GetPointResponseDto.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/dto/response/SearchRankingResponseDto.java
  benefit-service/src/main/java/com/waitless/benefit/point/presentation/mapper/PointControllerMapper.java
  benefit-service/src/main/resources/application.yml
  common/http-test/benefit/point.http
  common/src/main/java/com/waitless/common/config/QuerydslConfig.java
  common/src/main/java/com/waitless/common/constants/PointCacheConstants.java
  review-service/src/main/java/com/waitless/review/ReviewApplication.java
Labels: feature

#174 Feat/reservation 163 menu saga create
  common/src/main/java/com/waitless/common/dto/ReservationCancelEvent.java
  common/src/main/java/com/waitless/common/event/StockDecreasedEvent.java
  reservation-service/src/main/java/com/waitless/reservation/application/event/KafkaSlackEventProducer.java
  reservation-service/src/main/java/com/waitless/reservation/application/event/ReservationMessageEventHandler.java
  reservation-service/src/main/java/com/waitless/reservation/application/event/StockDecreaseEventProducer.java
  reservation-service/src/main/java/com/waitless/reservation/application/event/StockEventHandler.java
  reservation-service/src/main/java/com/waitless/reservation/application/event/dto/ReservationCancelRequestEvent.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/command/ReservationCommandServiceImpl.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/message/MessageService.java
  reservation-service/src/main/java/com/waitless/reservation/application/service/message/SlackMessageService.java
  reservation-service/src/main/java/com/waitless/reservation/infrastructure/adaptor/kafka/StockDecreaseKafkaListener.java
Labels: feature
